# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PnwRotPy
                                 A QGIS plugin
 Exploration of effect of NW rotation on YHS path
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-12-23
        copyright            : (C) 2025 by Steve White
        email                : stevewh@uw.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import os
import sys

# Get the path to your 'src' directory relative to this file
plugin_dir = os.path.dirname(__file__)
src_dir = os.path.abspath(os.path.join(plugin_dir, "src"))

# Add it to sys.path so QGIS can see 'import package'
if src_dir not in sys.path:
  sys.path.insert(0, src_dir)

# noinspection PyPep8Naming


def classFactory(iface):  # pylint: disable=invalid-name
  """Load PnwRotPy class from file PnwRotPy.

  :param iface: A QGIS interface instance.
  :type iface: QgsInterface
  """
  #
  from .pnw_rotation_py import PnwRotPy
  return PnwRotPy(iface)
